# This is GitHub Action for cross platform building
name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  builds:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run build
      env:
        TOXENV: build
      run: |
        pip install -r requirements-tests.txt
        tox
