# This is GitHub Action for linting and security check
name: CI
on:
  pull_request:
    branches: [master]

jobs:
  checks:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        env: [security, flake8, pylint]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run check
      env: 
        TOXENV: ${{ matrix.env }}
      run: |
        pip install -U tox
        tox