# This is GitHub Action for Continuous Intergration (CI)
name: CI
on:
  pull_request:
    branches: [master]

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04] # , macos-10.15, windows-latest
        python-version: ["3.10"]
        env: [base]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Continuous Integration (CI)
      env: 
        TOXENV: ${{ matrix.env }}
      run: |
        pip install -U tox
        tox
