# This is GitHub Action for cross platform building
name: docs
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build docs
      env:
        TOXENV: docs
      run: |
        pip install -r requirements-tests.txt
        tox
