name: main

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os  }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python: ["3.7", "3.8", "3.9"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-py

      - name: Run tox with ${{ matrix.python-version }}
        run: |
          tox --py current

