# This is GitHub Action for Continuous Intergration (CI)
name: Build Ubuntu
on:
  pull_request:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Continuous Integration (CI)
      env: 
        TOXENV: ubuntu
      run: |
        pip install -U tox
        tox
